version: '2'
services:
    reactster-app:
        image: reactster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://reactster-mysql:3306/reactster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    reactster-mysql:
        extends:
            file: mysql.yml
            service: reactster-mysql
